// Fixture data standing in for the real backend (GET /me, GET /applications
// don't exist yet). These are typed as WireApplication — the raw JSON shape,
// not the normalized one — so they can reproduce the things Go actually puts on
// the wire: `null` for a nil slice without omitempty, and a missing key for
// anything with omitempty. api.ts runs them through normalizeApplication() just
// like real responses, which keeps that path exercised in development instead
// of only discovered in production.
import type { User, WireApplication } from "./types";

export const mockUser: User = {
  id: "665f1c2e8a1b2c3d4e5f6a7b",
  email: "ada@example.com",
  name: "Ada Lovelace",
  created_at: "2026-06-01T09:00:00Z",
  updated_at: "2026-06-01T09:00:00Z",
};

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400000).toISOString();
}

export const mockApplications: WireApplication[] = [
  {
    id: "1",
    user_id: mockUser.id,
    company_name: "Acme Corp",
    position_title: "Backend Engineer",
    status: "applied",
    location: ["Remote"],
    job_link: "https://acme.example/jobs/123",
    job_description: "",
    tags: ["backend", "go"],
    notes: "",
    applied_at: daysAgo(2),
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "2",
    user_id: mockUser.id,
    company_name: "Globex",
    position_title: "Platform Engineer",
    status: "applied",
    location: ["Austin, TX"],
    job_link: "",
    job_description: "",
    tags: ["infra"],
    notes: "",
    applied_at: daysAgo(5),
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: "3",
    user_id: mockUser.id,
    company_name: "Initech",
    position_title: "Software Engineer II",
    status: "phone_screen",
    location: ["Remote"],
    job_link: "",
    job_description: "",
    tags: ["backend"],
    notes: "Recruiter call went well",
    applied_at: daysAgo(9),
    next_follow_up_at: daysAgo(-2),
    created_at: daysAgo(9),
    updated_at: daysAgo(1),
  },
  {
    id: "4",
    user_id: mockUser.id,
    company_name: "Umbrella Corp",
    position_title: "Senior Go Engineer",
    status: "phone_screen",
    location: ["Raleigh, NC", "Remote"],
    job_link: "",
    job_description: "",
    tags: ["go", "distributed-systems"],
    notes: "",
    applied_at: daysAgo(11),
    created_at: daysAgo(11),
    updated_at: daysAgo(11),
  },
  {
    id: "5",
    user_id: mockUser.id,
    company_name: "Stark Industries",
    position_title: "Infrastructure Engineer",
    status: "onsite",
    location: ["New York, NY"],
    job_link: "",
    job_description: "",
    tags: ["infra", "kubernetes"],
    notes: "Onsite scheduled for next week",
    applied_at: daysAgo(20),
    next_follow_up_at: daysAgo(-5),
    created_at: daysAgo(20),
    updated_at: daysAgo(3),
  },
  {
    id: "6",
    user_id: mockUser.id,
    company_name: "Wayne Enterprises",
    position_title: "Backend Engineer, Payments",
    status: "offer",
    location: ["Remote"],
    job_link: "",
    job_description: "",
    tags: ["backend", "payments"],
    notes: "Verbal offer received",
    compensation: {
      base_salary: 165000,
      bonus: 15000,
      equity: "$40k RSU / 4yr",
      benefits: ["health", "401k"],
    },
    applied_at: daysAgo(30),
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
  },
  {
    id: "7",
    user_id: mockUser.id,
    company_name: "Hooli",
    position_title: "Site Reliability Engineer",
    status: "rejected",
    location: ["Palo Alto, CA"],
    job_link: "",
    job_description: "",
    tags: ["sre"],
    notes: "Didn't move forward after onsite",
    applied_at: daysAgo(45),
    created_at: daysAgo(45),
    updated_at: daysAgo(15),
  },
  {
    // Deliberately the sparsest record in the set: `location` and `tags` are
    // null the way a nil Go slice serializes, and every omitempty field is
    // absent. If normalizeApplication() ever regresses, this row is what
    // throws first.
    id: "8",
    user_id: mockUser.id,
    company_name: "Soylent Corp",
    position_title: "Backend Engineer",
    status: "withdrawn",
    location: null,
    job_link: "",
    job_description: "",
    tags: null,
    notes: "Took the Wayne Enterprises offer",
    applied_at: daysAgo(25),
    created_at: daysAgo(25),
    updated_at: daysAgo(4),
  },
];
